// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Category struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedBy string    `json:"created_by"`
	IsVisible bool      `json:"is_visible"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Comment struct {
	ID        int32     `json:"id"`
	TopicID   int64     `json:"topic_id"`
	Body      string    `json:"body"`
	Points    int64     `json:"points"`
	CreatedBy string    `json:"created_by"`
	IsVisible bool      `json:"is_visible"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Reply struct {
	ID        int32     `json:"id"`
	CommentID int64     `json:"comment_id"`
	Body      string    `json:"body"`
	Points    int64     `json:"points"`
	CreatedBy string    `json:"created_by"`
	IsVisible bool      `json:"is_visible"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Topic struct {
	ID         int32     `json:"id"`
	CategoryID int64     `json:"category_id"`
	Title      string    `json:"title"`
	Body       string    `json:"body"`
	CreatedBy  string    `json:"created_by"`
	Points     int64     `json:"points"`
	IsVisible  bool      `json:"is_visible"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID             int32     `json:"id"`
	UserName       string    `json:"user_name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	IsBanned       bool      `json:"is_banned"`
	IsAdmin        bool      `json:"is_admin"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
