// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	BanUser(ctx context.Context, id int32) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) error
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetTopicByID(ctx context.Context, id int32) (Topic, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUserName(ctx context.Context, userName string) (User, error)
	HideTopicByID(ctx context.Context, id int32) error
	ListCategories(ctx context.Context) ([]Category, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	ListUsers(ctx context.Context) ([]User, error)
	SetAdmin(ctx context.Context, id int32) error
	UnBanUser(ctx context.Context, id int32) error
	UnSetAdmin(ctx context.Context, id int32) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateTopicByID(ctx context.Context, arg UpdateTopicByIDParams) error
}

var _ Querier = (*Queries)(nil)
