// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BanUser(ctx context.Context, id int32) error
	CountCommentsByTopicID(ctx context.Context, topicID int64) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecreaseCommentPointsByID(ctx context.Context, id int32) error
	DecreaseTopicPointsByID(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	FindCategory(ctx context.Context, name string) (Category, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetCommentByID(ctx context.Context, id int32) (Comment, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTopicByID(ctx context.Context, id int32) (Topic, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUserName(ctx context.Context, userName string) (User, error)
	HideCommentByID(ctx context.Context, id int32) error
	HideTopicByID(ctx context.Context, id int32) error
	IncreaseCommentPointsByID(ctx context.Context, id int32) error
	IncreaseTopicPointsByID(ctx context.Context, id int32) error
	ListCategories(ctx context.Context) ([]Category, error)
	ListCommentsByTopicID(ctx context.Context, topicID int64) ([]Comment, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	ListUsers(ctx context.Context) ([]User, error)
	SetAdmin(ctx context.Context, id int32) error
	UnBanUser(ctx context.Context, id int32) error
	UnSetAdmin(ctx context.Context, id int32) error
	UpdateCommentByID(ctx context.Context, arg UpdateCommentByIDParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateTopicByID(ctx context.Context, arg UpdateTopicByIDParams) error
}

var _ Querier = (*Queries)(nil)
